name: tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup project
      run: make setup

    - name: Migrate
      env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: test_db
          DB_USERNAME: test_user
          DB_PASSWORD: test
      run: make migrate

    - name: Check lint
      run: make lint

    - name: Run tests
      env:
            DB_CONNECTION: pgsql
            DB_HOST: localhost
            DB_PORT: 5432
            DB_DATABASE: test_db
            DB_USERNAME: test_user
            DB_PASSWORD: test
            QUEUE_CONNECTION: database
      run: make test